### ISSUE TITLE
Get cleaned data from clean_data 

### ISSUE THREAD

**Issue by NancyQin0503** [meilinli123/eco395m-MidtermProject#1]

**Comment by 221B-Baker-St** [comment]
I suppose the best way to clean for data is to:

Check missing data: Check for missing values in your dataset. You can use the .isnull() or .isna() functions to identify missing data and decide how to handle it. You might choose to drop rows with missing values or fill them in with appropriate values.

Check data types: Ensure that columns have the correct data types. Use the .astype() function to convert columns to the right data types if necessary.

Check duplicates: Check for duplicate rows in your dataset using .duplicated() and .drop_duplicates() to remove them if needed.

Outliers: Identify and handle outliers if they exist in your data. You can use statistical methods to detect outliers or domain knowledge to determine reasonable boundaries.

Chec data transformation: Perform any necessary data transformations, such as scaling, encoding categorical variables, or aggregating data as required for your analysis.
