### ISSUE TITLE
data request limit of facilities.csv is 10, there could be more or less, just use as fast request for 10

### ISSUE THREAD

**Issue by PlaneswalkerTeferi** [meilinli123/eco395m-MidtermProject#6]

**Comment by 221B-Baker-St** [comment]
Apologies I also just posted this issue, thank you for asking about it. I think its best to be kept at 10, 100 took a couple minutes and thus perhaps 10 is suffcient for light analysis purposes, but perhaps this should be mentioned in the limitations section of the paper. I'll make a note.
